name: Build Executables

on:
  push:
    tags:
      - 'v*.*.*'  # 匹配语义化版本标签 (例如 v1.0.0)

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - python_arch: x86
            exe_arch: x86
          - python_arch: x64
            exe_arch: x64

    steps:
      - uses: actions/checkout@v4

      - name: 提取版本号
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: 设置 Python ${{ matrix.python_arch }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: ${{ matrix.python_arch }}

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.7.0

      - name: 验证依赖版本
        run: |
          pip freeze | findstr "Pillow PyQt5 PyQt5-Qt5 PyQt5_sip"

      - name: 构建可执行文件
        run: |
          pyinstaller --onefile --noconsole --name Image2Array^
            --hidden-import PyQt5.QtCore^
            --hidden-import PyQt5.QtGui^
            --hidden-import PyQt5.QtWidgets^
            --paths .\venv\Lib\site-packages^
            image_converter.py

      - name: 重命名文件
        run: |
          ren dist\Image2Array.exe Image2Array-Win-${{ matrix.exe_arch }}-%VERSION%.exe
        shell: cmd
        env:
          VERSION: ${{ env.VERSION }}

      - name: 上传制品
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            dist/Image2Array-Win-${{ matrix.exe_arch }}-${{ env.VERSION }}.exe